### ISSUE TITLE
TypeError: this._icon.setNativeProps is not a function (it is undefined), js engine: hermes

### ISSUE THREAD

**Issue by forki** [web-ridge/react-native-paper-tabs#65] opened 2024-01-26 13:11 UTC
### Current behaviour

With expo SDK 50 we get:

`TypeError: this._icon.setNativeProps is not a function (it is undefined), js engine: hermes`

this happens when you change a tab and both tabs have Icons. If we remove the icons, then tab changing is still fine.

### Expected behaviour

App should not crash

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.73.2
| react-native-paper    | ~5.12.3
| expo sdk                     | SDK 50

**Comment by RichardLindhout** [comment] 2024-01-27 14:19
Should be fixed in newer release. Are you on latest version?

https://github.com/web-ridge/react-native-paper-tabs/commit/a85eaaf0f7fb3227a4a87b0808fda91495167813

**Closed by RichardLindhout** 2024-01-27 14:19 UTC
Labels: bug

**Comment by fwestling** [comment] 2024-02-16 04:18
I'm getting this error as well, just installed the library fresh.  Versions:

- expo: 50.0.6
- react-native-paper: 5.10.4
- react-native-paper-tabs: 0.10.3
- react-native-pager-view: 6.2.3

**Comment by Kinjalrk2k** [comment] 2024-02-22 19:24
Same issue on:
- expo: ~50.0.7
- react-native-paper: ^5.12.3
- react-native-paper-tabs: ^0.10.3
- react-native-pager-view: ^6.2.3

Any resolutions?

**Comment by riteshreg** [comment] 2024-02-27 11:53
same issue

**Comment by cyril36** [comment] 2024-03-10 03:28
### Same issue
I just had the same issue with version :
expo: ~50.0.11
"react-native-pager-view": "6.2.3",
"react-native-paper": "^5.11.0",
"react-native-paper-tabs": "^0.10.3",

### Fixed
I have install : 
"react-native-paper-tabs": "^0.10.4", (i dont think it change anything :D )
and explicitly installed :
`"@expo/vector-icons": "^13.0.0",`

And the issue is fixed :+1:

**Comment by RichardLindhout** [comment] 2025-01-07 21:32
This is fixed now by us using useNativeDriver: true + not animated color of icon on android (since that gives another strange error) and material you does not animate color of icon anyways anymore
